// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1zeXsxh7WdJB1j7oyAVUKZz3af3NSw1Q',
    appId: '1:521678456472:web:8669b8106add671475b2ed',
    messagingSenderId: '521678456472',
    projectId: 'new-chats-6303e',
    authDomain: 'new-chats-6303e.firebaseapp.com',
    storageBucket: 'new-chats-6303e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo4zMUq926RMqqylIar9qz615HFsMZhoU',
    appId: '1:521678456472:android:15679ff4785fe41f75b2ed',
    messagingSenderId: '521678456472',
    projectId: 'new-chats-6303e',
    storageBucket: 'new-chats-6303e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXNX_IhqN4h2-Qb6qVLNWj8P9qQwPJSxc',
    appId: '1:521678456472:ios:c55d71dddd6ee8ac75b2ed',
    messagingSenderId: '521678456472',
    projectId: 'new-chats-6303e',
    storageBucket: 'new-chats-6303e.appspot.com',
    iosBundleId: 'com.example.chats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXNX_IhqN4h2-Qb6qVLNWj8P9qQwPJSxc',
    appId: '1:521678456472:ios:9923ced7284a392475b2ed',
    messagingSenderId: '521678456472',
    projectId: 'new-chats-6303e',
    storageBucket: 'new-chats-6303e.appspot.com',
    iosBundleId: 'com.example.chats.RunnerTests',
  );
}
